name: telugu_bhagavatam_verse
description: Daily Telugu Bhagavatam verse widget app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  html: ^0.15.4
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  home_widget: ^0.6.0
  workmanager: ^0.5.2
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true