name: brain_app
description: Brain state labeling app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.10.4
  file_picker: ^8.1.2
  csv: ^6.0.0
  path_provider: ^2.1.3

flutter:
  assets:
    - assets/brain_model.tflite
    - assets/scaler.json