name = "BiofeedbackSystem"
uuid = "732fba53-ffbc-48f4-a360-89c0703e5b39"
authors = ["vamsimadhavtata <208189974+Anaspiringdesigner@users.noreply.github.com.>"]
version = "0.1.0"

[deps]
ReinforcementLearning = "158674fc-8238-5cab-b5ba-03dfc80d1318"

[compat]
ReinforcementLearning = "0.11.0"
